### PR TITLE
Fix handling of user-related course form errors

### PR DESCRIPTION
**Pull request by va7map**
These fixes address problems caused by deleted pseudonyms and invalid Computing IDs. Please see individual commit messages for details.

### CODE REVIEW

**Comment by patchin** [comment]
You've misspelled characters as charaters in commit 676a010.

**Comment by va7map** [comment]
Good catch! I've replaced https://github.com/sfu/canvas-lms/commit/676a0108645d080975df2946811bd2f3662ad0f9 with https://github.com/sfu/canvas-lms/commit/8f259e7e82e2cc8f139abeb5051f962097c58dbf.

**Comment by patchin** [comment]
@va7map Thanks! :+1:

**Comment by grahamb** [comment]
:rainbow:

**Pull request merged**
