### PR TITLE
convert sfu_api to a rails engine

### PR DESCRIPTION
**Pull request by grahamb**
Converts the sfu_api plugin into a rails engine in gems/plugins. Tests pass on vagrant:

```
vagrant@canvas:/vagrant$ RAILS_ENV=test bin/rspec gems/plugins/sfu_api
Bullet Instructure not enabled

Randomized with seed 42219

.........................................

Finished in 19.68 seconds
41 examples, 0 failures

Randomized with seed 42219
```

I also needed to change lib/aaa_sfu_misc/test_cluster.rb as it requires one of the files in sfu_api.

### CODE REVIEW

**Comment by va7map** [comment]
:rainbow:

**Comment by grahamb** [comment]
Note mostly for me: sfu/canvas-spaces needs to be updated as well; [manager-controller.rb](https://github.com/sfu/canvas-spaces/blob/master/app/controllers/manager_controller.rb#L1) requires part of the API plugin by path. This seems insane and we should figure out a way to not do that, if possible.

**Comment by patchin** [comment]
It might be easier now to require the sfu_api without the full path just as if it were a gem.

**Comment by patchin** [comment]
:rainbow:

**Pull request merged**
