### PR TITLE
Enable Canvas Spaces in nav, fix notifications

### PR DESCRIPTION
**Pull request by grahamb**
This does two things:

- adds a link to Canvas Spaces in the top nav, if the canvas_spaces plugin is enabled
- changes the URL in notifications to go to /groups instead of /accounts/:id/groups (which a normal user doesn't have access to)

### CODE REVIEW

**Comment by va7map** [comment]
:rainbow: The list of commits is quite long, but the diff looks good.

**Comment by grahamb** [comment]
Yeah, it's an old branch and had to be brought up to date a few times.

**Comment by GinnyGuo** [comment]
:rainbow:

**Comment by patchin** [comment]
:rainbow:

**Pull request merged**
