### PR TITLE
Add tests for the sfu_api plugin

### PR DESCRIPTION
**Pull request by grahamb**
This adds a test suite to the sfu_api plugin. The suite performs
functional tests on all of the routes described in config/routes.rb.

Test plan:

* clone this PR
* `vagrant up && vagrant ssh`
* `cd /vagrant && bundle exec rspec vendor/plugins/sfu_api`

All tests should pass; there should be no failures.

Going forward, all changes to the sfu_api must have passing tests.

### CODE REVIEW

**Comment by va7map** [comment]
Nice use of mocks! They are all passing tests in my VM.

The tests for [`AmaintController#sectionTutorials`](https://github.com/grahamb/canvas-lms/blob/c5e486e8344284149e7846e640ad00a77fd75362/vendor/plugins/sfu_api/spec/controllers/amaint_controller_spec.rb#L33) and [`#sections`](https://github.com/grahamb/canvas-lms/blob/c5e486e8344284149e7846e640ad00a77fd75362/vendor/plugins/sfu_api/spec/controllers/amaint_controller_spec.rb#L38) should expect different outputs, because `sectionTutorials` should return an array that excludes D100. There is an extra D100 `TUT` section in the [amaint_mock.yaml](https://github.com/grahamb/canvas-lms/blob/c5e486e8344284149e7846e640ad00a77fd75362/vendor/plugins/sfu_api/spec/mocks/amaint_mocks.yaml#L1), near the end. Removing that should reveal the distinction between the two methods.

**Comment by grahamb** [comment]
Thanks - I wasn't quite clear on the distinction between the two. I've pushed up a commit with the extra D100 removed and updated the sectionTutorials test.

**Comment by va7map** [comment]
:rainbow: Thanks! Retested and all green.

By the way, the last fix introduced a typo ("sachedules"), but it didn't affect the tests because schedule info's not being used anyway.

**Comment by grahamb** [comment]
Weird. Fixed the typo.

**Comment by patchin** [comment]
:rainbow:

**Pull request merged**
