### PR TITLE
add a sfu rake task to reset account settings after a clone

### PR DESCRIPTION
**Pull request by grahamb**
Our non-production environments are built by cloning the production environment. Certain settings and values need to be unique across environments. For example, Account.lti_guid is used to identify a specific Canvas installation to an external tool. Canvas Commons doesn't work when identical values are used across environments.

This rake task resets the values for Account.name and Account.lti_guid. It can be run manually (`bundle exec rake sfu:account_settings[stage_name])`, but will also be added to the capistrano deploy for the `testing`, `staging` and `cuttingedge` stages.

The rake tasks gets the values to use for Account.name and Account.lti_guid from `sfu.yml`. I've updated the file in `/usr/local/canvas/config/....`, so it's good to go. To test this on a vagrant box, once provisioned, edit `/vagrant/config/sfu.yml` and add an `account_settings` block:

```
account_settings:
  stage_name:
    name: 'Simon Fraser University (canvas.dev)'
    lti_guid: 'klasjdf9uhksdfha9821hklqwjhesado9fhasdfw98yr32.canvas.dev'
```

The above is an example. `stage_name` can be whatever you want. In reality, `sfu.yml` has stages `cuttingedge`, `testing` and `staging`, which correspond to canvas-edge, canvas-test and canvas-stage.

Once `sfu.yml` is set up:

* `bundle exec rake sfu:account_settings` should throw an error since you didn't specify a stage
* `bundle exec rake sfu:account_settings[blahblahblah]` should throw an error since `sfu.yml` doesn't contain a stage named `blahblahblah` 
* `bundle exec rake sfu:account_settings[stage_name]` (substitute whatever you called your stage in `sfu.yml` for `stage_name`) should succeed.

You can verify the settings worked by checking the values for `Account.default.name` and `Account.default.lti_guid` in the rails console or the database directly. They should match whatever you put in `sfu.yml`

### CODE REVIEW

**Comment by va7map** [comment]
:rainbow:

**Comment by grahamb** [comment]
I've updated this with the necessary changes to the capistrano scripts to have this done automatically on deploys to test/stage/edge.

**Comment by va7map** [comment]
Here's a fresh :rainbow: for the new commits

**Comment by GinnyGuo** [comment]
:rainbow:

**Pull request merged**
