### PR TITLE
Vagrantify Canvas

### PR DESCRIPTION
**Pull request by grahamb**
Here we go again…

There's proper documentation this time [(Vagrant.md)](https://github.com/grahamb/canvas-lms/blob/vagrant/Vagrant.md). Please clone this repo somewhere temporary and give it a try. I've left Ansible running in verbose mode for now; if there's any problems please gist or [hastebin](hastebin.com) the log output and put a link in the comments.

```
git clone https://github.com/grahamb/canvas-lms.git /tmp/canvas-lms
cd /tmp/canvas-lms
git checkout -b vagrant origin/vagrant
vagrant up
```

I'd especially like @patchin and @GinnyGuo to give this a try.

### CODE REVIEW

**Comment by grahamb** [comment]
I'm unsure why this can't be auto-merged; I'm looking into it.

**Comment by grahamb** [comment]
Ah, got it: I had to cherry pick https://github.com/instructure/canvas-lms/commit/c81bebbfdfb2db8d63c46839f584ec0f7902f25b (fixes some issues when running the initial DB setup), which was on master. Git can't do a fast-forward merge; it has to do it recursively. There's no conflicts, though.

Test away!

**Comment by grahamb** [comment]
One thing to be aware of (and this is why I suggest checking out into a temp location instead of using your existing repo dir to test this): this will overwrite several canvas config files (eg database.yml, etc -- see all of them [here](https://github.com/grahamb/canvas-lms/tree/vagrant/provision/canvas/templates)).

**Comment by va7map** [comment]
:+1: 

Tested on my machines. It worked great! The only extra thing I had to do was to check out the `vagrant` branch, because the default `sfu-develop` branch doesn't have any Vagrant stuff yet.

By the way, the pull request is showing that 81 files are changed, but in reality, you've only added/changed `Vagrantfile`, `Vagrant.md`, and `provision/*`, right?

**Comment by grahamb** [comment]
Yeah, those were the only things I added. I pulled in the Instructure hot fixes after we put them into prod; they're showing up as additional commits on this branch.

**Comment by GinnyGuo** [comment]
:+1:

**Comment by grahamb** [comment]
I'll manually merge this and push it up to sfu-develop.

**Pull request merged**
