### PR TITLE
Create React Components for Copyright Compliance and PIA notices

### PR DESCRIPTION
**Pull request by grahamb**
Work-in-progress to create React components for the Copyright Compliance and PIA notices. Don't vote yet; this isn't nearly complete.

## Copyright Compliance

- [x] create SFUCopyrightComplianceNotice (SFUCCN) component
- [x] create SFUCopyrightComplianceNoticeMoreInfo (SFUCCNMI) component
- [x] add a Read More… button to handle toggling the ...MoreInfo component
- [x] insert SFUCCN into the Course Wizard
- [x] display a modal with the SFUCCN when user clicks on the "Publish" button on the course home page

## PIA Notices
- [x] create SFUPrivacyNotice component
- [x] insert SFUPrivacyNotice component into the App Centre
- [x] insert SFUPrivacyNotice onto the course collaborations page

## Bonus Points
- [x] Replace the copyright notice in sfu_course_form plugin with SFUCopyrightComplianceNotice
- [x] remove the notice and related code from sfu_copyright plugin

### CODE REVIEW

**Comment by grahamb** [comment]
react-copyright-compliance

**Comment by grahamb** [comment]
I'm going to try to rework sfu.js to use the same requirejs build system as the rest of canvas, so it can pull in external components like the SFUCopyrightComplainceNotice.

**Comment by grahamb** [comment]
Code for this is still a bit janky and I need to clean it up before pushing, but…

publish_button

**Comment by grahamb** [comment]
happy_man

**Comment by va7map** [comment]
bravo

**Comment by grahamb** [comment]
Options for styling the PIA notice for LTI installation:

`alert alert-error`

alert-alert-error

`alert alert-info`

alert-alert-info

`alert`

alert

`well well-sm` (same as the blue box above it)

well-well-sm

@sfu/canvas-developers

**Comment by patchin** [comment]
I vote for alert alert-error.

**Comment by GinnyGuo** [comment]
Red +1

**Comment by va7map** [comment]
My vote is `alert` (yellow) because I tend to reserve red alerts for errors and destructive actions.

**Comment by grahamb** [comment]
If we do yellow I'll tweak the font colour so there's more contrast. It looks a bit pukey as-is.

**Comment by GinnyGuo** [comment]
Maybe ask Eryn? She is a good designer :)

**Comment by grahamb** [comment]
OK, yellow with slightly darker text.
screen shot 2015-02-20 at 10 29 27

**Comment by grahamb** [comment]
I was able to get the copyright notice component to render in the new course form as well.

newcourse

We should be able to remove the disclaimer code from the sfu_copyright plugin now.

**Comment by grahamb** [comment]
The only two places where we're touching Instructure's code here are:
[app/jsx/course_wizard/InfoFrame.jsx](https://github.com/sfu/canvas-lms/pull/201/files#diff-6bd0f9ab293628cdaa6cad28c8608856)
[app/jsx/external_apps/components/Header.jsx](https://github.com/sfu/canvas-lms/pull/201/files#diff-751130b6848996905c9263e5dfa817de)

**Comment by grahamb** [comment]
This is now "done", so I'm opening it up for voting. Assuming it passes, I'll squash everything down into one commit and merge it manually, rather than bring in 30 individual commits.

**Comment by grahamb** [comment]
I've opened #202 as a squashed version of this. Please vote there.

**Comment by GinnyGuo** [comment]
:+1:

**Pull request closed without merging**
