### PR TITLE
SFU Mods for the New UI

### PR DESCRIPTION
**Pull request by grahamb**
This PR implements all the changes needed to support the new Canvas User Interface ("new UI") in the SFU environment. 
- 9ff3cfe: refactors `sfu.js` to move new/old-UI specific features behind feature flags, and removes some old unused code
- 16b0ccb: removes old collaboration space (pre-Canvas Spaces) files
- ba33c27: adds a `sfu-newui.css` file containing the styles needed under the new UI.
- 6b3d755: makes `brandable_css` work in the SFU setup (read the commit message, it's a doozy)
- 84657cb: adds a simple plugin to override the default Instructure help links

Once merged, the new UI still needs to be enabled in the target environment, and the theme editor needs to be used to upload the JS and CSS files.

### CODE REVIEW

**Comment by grahamb** [comment]
For posterity, since it scrolled behind the Slack paywall: the setting to enable the help menu is `
`show_feedback_link`

**Comment by patchin** [comment]
:rainbow:

**Comment by GinnyGuo** [comment]
🌈

**Comment by va7map** [comment]
Extra :rainbow:!

**Pull request merged**
